// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

public interface purchaseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:purchaseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainRoute = 1;</code>
   */
  java.lang.String getTrainRoute();
  /**
   * <code>string trainRoute = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainRouteBytes();
}
