// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

public interface ticketDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticketDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmed = 1;</code>
   */
  java.lang.String getConfirmed();
  /**
   * <code>string confirmed = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmedBytes();
}
