// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

/**
 * Protobuf type {@code ticketsAvailable}
 */
public  final class ticketsAvailable extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ticketsAvailable)
    ticketsAvailableOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ticketsAvailable.newBuilder() to construct.
  private ticketsAvailable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ticketsAvailable() {
    ticketDetail_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ticketsAvailable(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ticketDetail_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.transportSystem.grpc.TicketProto.internal_static_ticketsAvailable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.transportSystem.grpc.TicketProto.internal_static_ticketsAvailable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.transportSystem.grpc.ticketsAvailable.class, com.transportSystem.grpc.ticketsAvailable.Builder.class);
  }

  public static final int TICKETDETAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object ticketDetail_;
  /**
   * <code>string ticketDetail = 1;</code>
   */
  public java.lang.String getTicketDetail() {
    java.lang.Object ref = ticketDetail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ticketDetail_ = s;
      return s;
    }
  }
  /**
   * <code>string ticketDetail = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTicketDetailBytes() {
    java.lang.Object ref = ticketDetail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticketDetail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTicketDetailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ticketDetail_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTicketDetailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ticketDetail_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.transportSystem.grpc.ticketsAvailable)) {
      return super.equals(obj);
    }
    com.transportSystem.grpc.ticketsAvailable other = (com.transportSystem.grpc.ticketsAvailable) obj;

    boolean result = true;
    result = result && getTicketDetail()
        .equals(other.getTicketDetail());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TICKETDETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getTicketDetail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.transportSystem.grpc.ticketsAvailable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.transportSystem.grpc.ticketsAvailable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ticketsAvailable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ticketsAvailable)
      com.transportSystem.grpc.ticketsAvailableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.transportSystem.grpc.TicketProto.internal_static_ticketsAvailable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.transportSystem.grpc.TicketProto.internal_static_ticketsAvailable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.transportSystem.grpc.ticketsAvailable.class, com.transportSystem.grpc.ticketsAvailable.Builder.class);
    }

    // Construct using com.transportSystem.grpc.ticketsAvailable.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ticketDetail_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.transportSystem.grpc.TicketProto.internal_static_ticketsAvailable_descriptor;
    }

    @java.lang.Override
    public com.transportSystem.grpc.ticketsAvailable getDefaultInstanceForType() {
      return com.transportSystem.grpc.ticketsAvailable.getDefaultInstance();
    }

    @java.lang.Override
    public com.transportSystem.grpc.ticketsAvailable build() {
      com.transportSystem.grpc.ticketsAvailable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.transportSystem.grpc.ticketsAvailable buildPartial() {
      com.transportSystem.grpc.ticketsAvailable result = new com.transportSystem.grpc.ticketsAvailable(this);
      result.ticketDetail_ = ticketDetail_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.transportSystem.grpc.ticketsAvailable) {
        return mergeFrom((com.transportSystem.grpc.ticketsAvailable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.transportSystem.grpc.ticketsAvailable other) {
      if (other == com.transportSystem.grpc.ticketsAvailable.getDefaultInstance()) return this;
      if (!other.getTicketDetail().isEmpty()) {
        ticketDetail_ = other.ticketDetail_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.transportSystem.grpc.ticketsAvailable parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.transportSystem.grpc.ticketsAvailable) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ticketDetail_ = "";
    /**
     * <code>string ticketDetail = 1;</code>
     */
    public java.lang.String getTicketDetail() {
      java.lang.Object ref = ticketDetail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticketDetail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ticketDetail = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTicketDetailBytes() {
      java.lang.Object ref = ticketDetail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticketDetail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ticketDetail = 1;</code>
     */
    public Builder setTicketDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ticketDetail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ticketDetail = 1;</code>
     */
    public Builder clearTicketDetail() {
      
      ticketDetail_ = getDefaultInstance().getTicketDetail();
      onChanged();
      return this;
    }
    /**
     * <code>string ticketDetail = 1;</code>
     */
    public Builder setTicketDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ticketDetail_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ticketsAvailable)
  }

  // @@protoc_insertion_point(class_scope:ticketsAvailable)
  private static final com.transportSystem.grpc.ticketsAvailable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.transportSystem.grpc.ticketsAvailable();
  }

  public static com.transportSystem.grpc.ticketsAvailable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ticketsAvailable>
      PARSER = new com.google.protobuf.AbstractParser<ticketsAvailable>() {
    @java.lang.Override
    public ticketsAvailable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ticketsAvailable(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ticketsAvailable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ticketsAvailable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.transportSystem.grpc.ticketsAvailable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

