// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

public interface ticketsAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ticketsAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticketDetail = 1;</code>
   */
  java.lang.String getTicketDetail();
  /**
   * <code>string ticketDetail = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketDetailBytes();
}
