// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

public final class TicketProto {
  private TicketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_purchaseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_purchaseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ticketDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ticketDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainRoute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trainRoute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ticketsAvailable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ticketsAvailable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ticket.proto\"\"\n\014purchaseInfo\022\022\n\ntrainR" +
      "oute\030\001 \001(\t\"\"\n\rticketDetails\022\021\n\tconfirmed" +
      "\030\001 \001(\t\"\033\n\ntrainRoute\022\r\n\005route\030\001 \001(\t\"(\n\020t" +
      "icketsAvailable\022\024\n\014ticketDetail\030\001 \001(\t2p\n" +
      "\007tickets\022*\n\tbuyTicket\022\r.purchaseInfo\032\016.t" +
      "icketDetails\0229\n\025checkAvailableTickets\022\013." +
      "trainRoute\032\021.ticketsAvailable0\001B)\n\030com.t" +
      "ransportSystem.grpcB\013TicketProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_purchaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_purchaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_purchaseInfo_descriptor,
        new java.lang.String[] { "TrainRoute", });
    internal_static_ticketDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ticketDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ticketDetails_descriptor,
        new java.lang.String[] { "Confirmed", });
    internal_static_trainRoute_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trainRoute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trainRoute_descriptor,
        new java.lang.String[] { "Route", });
    internal_static_ticketsAvailable_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ticketsAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ticketsAvailable_descriptor,
        new java.lang.String[] { "TicketDetail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
