// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetables.proto

package com.transportSystem.grpc;

public final class TimetableProto {
  private TimetableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface trainRideOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trainRide)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string route = 1;</code>
     */
    java.lang.String getRoute();
    /**
     * <code>string route = 1;</code>
     */
    com.google.protobuf.ByteString
        getRouteBytes();
  }
  /**
   * Protobuf type {@code trainRide}
   */
  public  static final class trainRide extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trainRide)
      trainRideOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use trainRide.newBuilder() to construct.
    private trainRide(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private trainRide() {
      route_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private trainRide(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              route_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.transportSystem.grpc.TimetableProto.internal_static_trainRide_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.transportSystem.grpc.TimetableProto.internal_static_trainRide_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.transportSystem.grpc.TimetableProto.trainRide.class, com.transportSystem.grpc.TimetableProto.trainRide.Builder.class);
    }

    public static final int ROUTE_FIELD_NUMBER = 1;
    private volatile java.lang.Object route_;
    /**
     * <code>string route = 1;</code>
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        route_ = s;
        return s;
      }
    }
    /**
     * <code>string route = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRouteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, route_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRouteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, route_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.transportSystem.grpc.TimetableProto.trainRide)) {
        return super.equals(obj);
      }
      com.transportSystem.grpc.TimetableProto.trainRide other = (com.transportSystem.grpc.TimetableProto.trainRide) obj;

      boolean result = true;
      result = result && getRoute()
          .equals(other.getRoute());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRoute().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainRide parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.transportSystem.grpc.TimetableProto.trainRide prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trainRide}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trainRide)
        com.transportSystem.grpc.TimetableProto.trainRideOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainRide_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainRide_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.transportSystem.grpc.TimetableProto.trainRide.class, com.transportSystem.grpc.TimetableProto.trainRide.Builder.class);
      }

      // Construct using com.transportSystem.grpc.TimetableProto.trainRide.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        route_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainRide_descriptor;
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainRide getDefaultInstanceForType() {
        return com.transportSystem.grpc.TimetableProto.trainRide.getDefaultInstance();
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainRide build() {
        com.transportSystem.grpc.TimetableProto.trainRide result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainRide buildPartial() {
        com.transportSystem.grpc.TimetableProto.trainRide result = new com.transportSystem.grpc.TimetableProto.trainRide(this);
        result.route_ = route_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.transportSystem.grpc.TimetableProto.trainRide) {
          return mergeFrom((com.transportSystem.grpc.TimetableProto.trainRide)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.transportSystem.grpc.TimetableProto.trainRide other) {
        if (other == com.transportSystem.grpc.TimetableProto.trainRide.getDefaultInstance()) return this;
        if (!other.getRoute().isEmpty()) {
          route_ = other.route_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.transportSystem.grpc.TimetableProto.trainRide parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.transportSystem.grpc.TimetableProto.trainRide) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object route_ = "";
      /**
       * <code>string route = 1;</code>
       */
      public java.lang.String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          route_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string route = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRouteBytes() {
        java.lang.Object ref = route_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          route_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder setRoute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        route_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder clearRoute() {
        
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      /**
       * <code>string route = 1;</code>
       */
      public Builder setRouteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        route_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trainRide)
    }

    // @@protoc_insertion_point(class_scope:trainRide)
    private static final com.transportSystem.grpc.TimetableProto.trainRide DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.transportSystem.grpc.TimetableProto.trainRide();
    }

    public static com.transportSystem.grpc.TimetableProto.trainRide getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<trainRide>
        PARSER = new com.google.protobuf.AbstractParser<trainRide>() {
      @java.lang.Override
      public trainRide parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new trainRide(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<trainRide> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<trainRide> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.transportSystem.grpc.TimetableProto.trainRide getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface trainTimetablesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trainTimetables)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string timetables = 1;</code>
     */
    java.lang.String getTimetables();
    /**
     * <code>string timetables = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimetablesBytes();
  }
  /**
   * Protobuf type {@code trainTimetables}
   */
  public  static final class trainTimetables extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trainTimetables)
      trainTimetablesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use trainTimetables.newBuilder() to construct.
    private trainTimetables(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private trainTimetables() {
      timetables_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private trainTimetables(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              timetables_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.transportSystem.grpc.TimetableProto.internal_static_trainTimetables_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.transportSystem.grpc.TimetableProto.internal_static_trainTimetables_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.transportSystem.grpc.TimetableProto.trainTimetables.class, com.transportSystem.grpc.TimetableProto.trainTimetables.Builder.class);
    }

    public static final int TIMETABLES_FIELD_NUMBER = 1;
    private volatile java.lang.Object timetables_;
    /**
     * <code>string timetables = 1;</code>
     */
    public java.lang.String getTimetables() {
      java.lang.Object ref = timetables_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timetables_ = s;
        return s;
      }
    }
    /**
     * <code>string timetables = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimetablesBytes() {
      java.lang.Object ref = timetables_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timetables_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimetablesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timetables_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimetablesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timetables_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.transportSystem.grpc.TimetableProto.trainTimetables)) {
        return super.equals(obj);
      }
      com.transportSystem.grpc.TimetableProto.trainTimetables other = (com.transportSystem.grpc.TimetableProto.trainTimetables) obj;

      boolean result = true;
      result = result && getTimetables()
          .equals(other.getTimetables());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMETABLES_FIELD_NUMBER;
      hash = (53 * hash) + getTimetables().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.transportSystem.grpc.TimetableProto.trainTimetables parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.transportSystem.grpc.TimetableProto.trainTimetables prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trainTimetables}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trainTimetables)
        com.transportSystem.grpc.TimetableProto.trainTimetablesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainTimetables_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainTimetables_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.transportSystem.grpc.TimetableProto.trainTimetables.class, com.transportSystem.grpc.TimetableProto.trainTimetables.Builder.class);
      }

      // Construct using com.transportSystem.grpc.TimetableProto.trainTimetables.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timetables_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.transportSystem.grpc.TimetableProto.internal_static_trainTimetables_descriptor;
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainTimetables getDefaultInstanceForType() {
        return com.transportSystem.grpc.TimetableProto.trainTimetables.getDefaultInstance();
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainTimetables build() {
        com.transportSystem.grpc.TimetableProto.trainTimetables result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.transportSystem.grpc.TimetableProto.trainTimetables buildPartial() {
        com.transportSystem.grpc.TimetableProto.trainTimetables result = new com.transportSystem.grpc.TimetableProto.trainTimetables(this);
        result.timetables_ = timetables_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.transportSystem.grpc.TimetableProto.trainTimetables) {
          return mergeFrom((com.transportSystem.grpc.TimetableProto.trainTimetables)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.transportSystem.grpc.TimetableProto.trainTimetables other) {
        if (other == com.transportSystem.grpc.TimetableProto.trainTimetables.getDefaultInstance()) return this;
        if (!other.getTimetables().isEmpty()) {
          timetables_ = other.timetables_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.transportSystem.grpc.TimetableProto.trainTimetables parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.transportSystem.grpc.TimetableProto.trainTimetables) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object timetables_ = "";
      /**
       * <code>string timetables = 1;</code>
       */
      public java.lang.String getTimetables() {
        java.lang.Object ref = timetables_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timetables_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timetables = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimetablesBytes() {
        java.lang.Object ref = timetables_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timetables_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timetables = 1;</code>
       */
      public Builder setTimetables(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timetables_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timetables = 1;</code>
       */
      public Builder clearTimetables() {
        
        timetables_ = getDefaultInstance().getTimetables();
        onChanged();
        return this;
      }
      /**
       * <code>string timetables = 1;</code>
       */
      public Builder setTimetablesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timetables_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trainTimetables)
    }

    // @@protoc_insertion_point(class_scope:trainTimetables)
    private static final com.transportSystem.grpc.TimetableProto.trainTimetables DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.transportSystem.grpc.TimetableProto.trainTimetables();
    }

    public static com.transportSystem.grpc.TimetableProto.trainTimetables getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<trainTimetables>
        PARSER = new com.google.protobuf.AbstractParser<trainTimetables>() {
      @java.lang.Override
      public trainTimetables parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new trainTimetables(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<trainTimetables> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<trainTimetables> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.transportSystem.grpc.TimetableProto.trainTimetables getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainRide_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trainRide_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trainTimetables_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trainTimetables_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020timetables.proto\"\032\n\ttrainRide\022\r\n\005route" +
      "\030\001 \001(\t\"%\n\017trainTimetables\022\022\n\ntimetables\030" +
      "\001 \001(\t2>\n\ttimetable\0221\n\rgetTimetables\022\n.tr" +
      "ainRide\032\020.trainTimetables\"\000(\001B*\n\030com.tra" +
      "nsportSystem.grpcB\016TimetableProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trainRide_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trainRide_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trainRide_descriptor,
        new java.lang.String[] { "Route", });
    internal_static_trainTimetables_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trainTimetables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trainTimetables_descriptor,
        new java.lang.String[] { "Timetables", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
