// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.transportSystem.grpc;

public interface trainRouteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trainRoute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string route = 1;</code>
   */
  java.lang.String getRoute();
  /**
   * <code>string route = 1;</code>
   */
  com.google.protobuf.ByteString
      getRouteBytes();
}
